using System.Text.Json.Serialization;
using WateryTart.MusicAssistant.Events;
using WateryTart.MusicAssistant.Messages;
using WateryTart.MusicAssistant.Models;
using WateryTart.MusicAssistant.Models.Auth;
using WateryTart.MusicAssistant.Models.Enums;
using WateryTart.MusicAssistant.Responses;

namespace WateryTart.MusicAssistant;

/*

IMPORTANT!!!

Unfortunately this file cannot be moved to a source generator, because System.Text.Json's source generator requires the context class to be in the same assembly as the types being serialized. 
This is a limitation of the System.Text.Json source generator, I'm unsure that can be worked around. 

*/
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
    PropertyNameCaseInsensitive = true,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    WriteIndented = false)]
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(List<object>))]
[JsonSerializable(typeof(string[]))]
[JsonSerializable(typeof(List<Item>))]
[JsonSerializable(typeof(List<Album>))]
[JsonSerializable(typeof(List<Artist>))]
[JsonSerializable(typeof(List<Playlist>))]
[JsonSerializable(typeof(List<Recommendation>))]
[JsonSerializable(typeof(List<Player>))]
[JsonSerializable(typeof(List<PlayerQueue>))]
[JsonSerializable(typeof(List<QueuedItem>))]
[JsonSerializable(typeof(List<Image>))]
[JsonSerializable(typeof(List<ProviderMapping>))]
[JsonSerializable(typeof(List<MetadataLink>))]
[JsonSerializable(typeof(List<List<string>>))]
[JsonSerializable(typeof(Auth))]
[JsonSerializable(typeof(Message))]
[JsonSerializable(typeof(Album))]
[JsonSerializable(typeof(Item))]
[JsonSerializable(typeof(MediaItemBase))]



//Insert stuff from autogenerated version here
[JsonSerializable(typeof(BaseEventResponse))]
[JsonSerializable(typeof(MediaItemEventItem))]
[JsonSerializable(typeof(MediaItemEvent2Item))]
[JsonSerializable(typeof(MediaItemEventResponse))]
[JsonSerializable(typeof(MediaItemEvent2Response))]
[JsonSerializable(typeof(PlayerEventResponse))]
[JsonSerializable(typeof(PlayerQueueEventResponse))]
[JsonSerializable(typeof(PlayerQueueTimeUpdatedEventResponse))]
[JsonSerializable(typeof(Auth))]
[JsonSerializable(typeof(Message))]
[JsonSerializable(typeof(Album))]
[JsonSerializable(typeof(Artist))]
[JsonSerializable(typeof(AudioFormat))]
[JsonSerializable(typeof(CurrentMedia))]
[JsonSerializable(typeof(DeviceInfo))]
[JsonSerializable(typeof(ExtraAttributes))]
[JsonSerializable(typeof(ExtraData))]
[JsonSerializable(typeof(Image))]
[JsonSerializable(typeof(Item))]
[JsonSerializable(typeof(Link))]
[JsonSerializable(typeof(MediaItem))]
[JsonSerializable(typeof(Metadata))]
[JsonSerializable(typeof(MetadataLink))]
[JsonSerializable(typeof(Player))]
[JsonSerializable(typeof(PlayerQueue))]
[JsonSerializable(typeof(Playlist))]
[JsonSerializable(typeof(ProviderMapping))]
[JsonSerializable(typeof(QueuedItem))]
[JsonSerializable(typeof(Recommendation))]
[JsonSerializable(typeof(Search))]
[JsonSerializable(typeof(SourceList))]
[JsonSerializable(typeof(Streamdetails))]
[JsonSerializable(typeof(AuthUser))]
[JsonSerializable(typeof(LoginResults))]
[JsonSerializable(typeof(MusicAssistantCredentials))]
[JsonSerializable(typeof(User))]
[JsonSerializable(typeof(EventType))]
[JsonSerializable(typeof(ImageType))]
[JsonSerializable(typeof(MediaType))]
[JsonSerializable(typeof(PlaybackState))]
[JsonSerializable(typeof(PlayMode))]
[JsonSerializable(typeof(AlbumResponse))]
[JsonSerializable(typeof(AlbumsResponse))]
[JsonSerializable(typeof(ArtistResponse))]
[JsonSerializable(typeof(ArtistsResponse))]
[JsonSerializable(typeof(AuthResponse))]
[JsonSerializable(typeof(CountResponse))]
[JsonSerializable(typeof(PlayerQueueItemsResponse))]
[JsonSerializable(typeof(PlayerQueueResponse))]
[JsonSerializable(typeof(PlayerResponse))]
[JsonSerializable(typeof(PlayersQueuesResponse))]
[JsonSerializable(typeof(PlaylistResponse))]
[JsonSerializable(typeof(PlaylistsResponse))]
[JsonSerializable(typeof(RecommendationResponse))]
[JsonSerializable(typeof(SearchResponse))]
[JsonSerializable(typeof(TempResponse))]
[JsonSerializable(typeof(TracksResponse))]
[JsonSerializable(typeof(ResponseBase<int>))]
[JsonSerializable(typeof(ResponseBase<object>))]
[JsonSerializable(typeof(ResponseBase<MediaItem>))]
[JsonSerializable(typeof(ResponseBase<Item>))]
[JsonSerializable(typeof(ResponseBase<MediaItemBase>))]
[JsonSerializable(typeof(ItemResponse))]

[JsonSerializable(typeof(ResponseBase<System.Collections.Generic.List<Album>>))]
[JsonSerializable(typeof(ResponseBase<System.Collections.Generic.List<Artist>>))]
[JsonSerializable(typeof(ResponseBase<System.Collections.Generic.List<Item>>))]
[JsonSerializable(typeof(ResponseBase<System.Collections.Generic.List<Player>>))]
[JsonSerializable(typeof(ResponseBase<System.Collections.Generic.List<PlayerQueue>>))]
[JsonSerializable(typeof(ResponseBase<System.Collections.Generic.List<Playlist>>))]
[JsonSerializable(typeof(ResponseBase<System.Collections.Generic.List<QueuedItem>>))]
[JsonSerializable(typeof(ResponseBase<System.Collections.Generic.List<Recommendation>>))]
[JsonSerializable(typeof(ResponseBase<Album>))]
[JsonSerializable(typeof(ResponseBase<Artist>))]
[JsonSerializable(typeof(ResponseBase<AuthUser>))]
[JsonSerializable(typeof(ResponseBase<PlayerQueue>))]
[JsonSerializable(typeof(ResponseBase<Playlist>))]
[JsonSerializable(typeof(ResponseBase<Search>))]
[JsonSerializable(typeof(UserResponse))]
[JsonSerializable(typeof(AuthToken))]
[JsonSerializable(typeof(ItemsListingArtistalbumsArtistalbums))]
[JsonSerializable(typeof(Provider))]
[JsonSerializable(typeof(UserPreferences))]
[JsonSerializable(typeof(ResponseBase<List<AuthToken>>))]
[JsonSerializable(typeof(ResponseBase<Provider>))]
[JsonSerializable(typeof(ResponseBase<string>))]
[JsonSerializable(typeof(ResponseBase<User>))]
public partial class MediaAssistantJsonContext : JsonSerializerContext
{
}

