using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace WateryTart.MusicAssistant.Generators;

[Generator]
public class NotifyPropertyChangedSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all class declarations with attributes
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (s, _) => s is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0,
                transform: (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
            .Where(cds => cds != null);

        // Pair class declaration with semantic model
        var classSymbols = context.CompilationProvider.Combine(classDeclarations.Collect());

        context.RegisterSourceOutput(classSymbols, (spc, source) =>
        {
            var (compilation, classDecls) = source;
            var inpcAttrName = "WateryTart.MusicAssistant.Generators.Attributes.NotifyPropertyChangedAttribute";
            var inpcPropAttrName = "WateryTart.MusicAssistant.Generators.Attributes.NotifyingPropertyAttribute";
            var inpcAlsoForAttrName = "WateryTart.MusicAssistant.Generators.Attributes.AlsoNotifyFor";

            foreach (var classDecl in classDecls)
            {
                var model = compilation.GetSemanticModel(classDecl.SyntaxTree);
                var classSymbol = model.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
                if (classSymbol == null)
                    continue;

                if (!classSymbol.GetAttributes().Any(ad =>
                    ad.AttributeClass?.ToDisplayString() == inpcAttrName))
                    continue;

                var ns = classSymbol.ContainingNamespace.IsGlobalNamespace
                    ? ""
                    : $"namespace {classSymbol.ContainingNamespace.ToDisplayString()}\n{{\n";

                var className = classSymbol.Name;
                // Only properties with [INPCProperty]
                var props = classSymbol.GetMembers()
                    .OfType<IPropertySymbol>()
                    .Where(p => !p.IsReadOnly && !p.IsStatic &&
                        p.GetAttributes().Any(ad => ad.AttributeClass?.ToDisplayString() == inpcPropAttrName))
                    .ToList();

                if (props.Count == 0)
                    continue; // No marked properties, skip generation

                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                if (!string.IsNullOrEmpty(ns)) sb.AppendLine(ns); // namespace opening
                sb.AppendLine($"public partial class {className} : System.ComponentModel.INotifyPropertyChanged");
                sb.AppendLine("{");
                sb.AppendLine("    public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;");
                sb.AppendLine("    protected void OnPropertyChanged(string propertyName) => PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));");

                foreach (var prop in props)
                {
                    // Inside your foreach (var prop in props) loop:
                    var type = prop.Type.ToDisplayString();
                    var name = prop.Name;
                    var field = $"_{char.ToLowerInvariant(name[0])}{name.Substring(1)}";

                    // Find all [INPCAlsoFor] attributes and collect their PropertyName arguments
                    var alsoFor = prop.GetAttributes()
                        .Where(ad => ad.AttributeClass?.ToDisplayString() == inpcAlsoForAttrName)
                        .Select(ad => ad.ConstructorArguments.FirstOrDefault().Value as string)
                        .Where(s => !string.IsNullOrEmpty(s))
                        .ToList();

                    sb.AppendLine($"    private {type} {field};");
                    sb.AppendLine($"    public partial {type} {name}");
                    sb.AppendLine("    {");
                    sb.AppendLine($"        get => {field};");
                    sb.AppendLine($"        set {{ if (!Equals({field}, value)) {{ {field} = value; OnPropertyChanged(nameof({name}));");

                    foreach (var also in alsoFor)
                        sb.AppendLine($"            OnPropertyChanged(\"{also}\");");

                    sb.AppendLine("        } } }");
                    //sb.AppendLine("    }");
                }

                sb.AppendLine("}"); // class closing
                if (!string.IsNullOrEmpty(ns)) sb.AppendLine("}"); // namespace closing

                spc.AddSource($"{className}_INPC.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            }
        });
    }
}